[package]
name = "agarust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "*"

[build-dependencies]
prost-build = "*"

[profile.release]
lto = true
strip = true
panic = "abort"
codegen-units = 1
