// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Packet {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(oneof = "packet::Data", tags = "2, 3")]
    pub data: ::core::option::Option<packet::Data>,
}
/// Nested message and enum types in `Packet`.
pub mod packet {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "2")]
        Hello(super::Hello),
        #[prost(message, tag = "3")]
        Chat(super::Chat),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Hello {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Chat {
    #[prost(string, tag = "1")]
    pub msg: ::prost::alloc::string::String,
}
