CREATE TABLE IF NOT EXISTS auth (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS player (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    auth_id INTEGER NOT NULL,
    nickname TEXT NOT NULL UNIQUE,
    color INTEGER NOT NULL,
    best_score INTEGER NOT NULL DEFAULT 0
);
